name: alfred_tutorial_1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  alfred:
  json_annotation: ^4.4.0
  dbcrypt: ^2.0.0
  corsac_jwt: ^1.0.0-nullsafety.1
  get_it: ^7.2.0
  mongo_dart: ^0.7.4

dev_dependencies:
  build_runner:
  json_serializable:
  test:
  http: